import type { Metadata } from "next";
import {Archivo_Black, Gravitas_One, Henny_Penny, Lobster_Two } from "next/font/google";
import "./globals.css";


const handWritten_Cursive=Lobster_Two({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Comment.Io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased bg-yellow-50 ${handWritten_Cursive.className}`}
      >
        {children}
      </body>
    </html>
  );
}
